version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10.12

    steps:
      - checkout

      - run:
        name: Install Dependencies
        command: pip install -r requirements.txt

      - run:
        name: Run Tests
        command: pytest

workflows:
  version: 2
  build:
    jobs:
      - build
